name: 🐛 Bug Report
description: Report a bug or unexpected behavior in the Scientific Data Viewer extension
title: "[Bug]: "
labels: ["bug", "needs-triage"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to report a bug! Please provide as much information as possible to help us reproduce and fix the issue.

  - type: input
    id: extension-version
    attributes:
      label: Extension Version
      description: What version of the Scientific Data Viewer extension are you using?
      placeholder: e.g., 0.2.0
    validations:
      required: true

  - type: input
    id: vscode-version
    attributes:
      label: VSCode Version or Cursor Version
      description: What version of VSCode or Cursor are you using?
      placeholder: e.g., 1.85.0
    validations:
      required: true

  - type: input
    id: os-version
    attributes:
      label: Operating System
      description: What operating system are you using?
      placeholder: e.g., Windows 11, macOS 14.0, Ubuntu 22.04
    validations:
      required: true

  - type: textarea
    id: bug-description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: Describe what happened and what you expected to happen.
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen.
    validations:
      required: true

  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual Behavior
      description: A clear and concise description of what actually happened.
    validations:
      required: true

  - type: textarea
    id: file-information
    attributes:
      label: File Information
      description: Information about the file(s) you were trying to open
      placeholder: |
        - File format: (e.g., NetCDF, HDF5, Zarr, GRIB, GeoTIFF)
        - File size: (e.g., 50 MB)
        - File path: (if possible, without sensitive information)
        - How was the file created? (e.g., generated by xarray, downloaded from...)
    validations:
      required: false

  - type: textarea
    id: python-environment
    attributes:
      label: Python Environment Information
      description: Please run the following command and paste the output here
      placeholder: |
        Run this command in your terminal and paste the output:
        python -c "import xarray as xr; print(xr.show_versions())"
    validations:
      required: false

  - type: textarea
    id: extension-config
    attributes:
      label: Extension Configuration
      description: Please share your Scientific Data Viewer extension settings
      placeholder: |
        Go to VSCode Settings (Ctrl+,) and search for "Scientific Data Viewer", then copy the relevant settings:
        - scientificDataViewer.maxFileSize: 
        - scientificDataViewer.allowMultipleTabsForSameFile: 
        - scientificDataViewer.plottingCapabilities:
    validations:
      required: false

  - type: textarea
    id: extension-logs
    attributes:
      label: Extension Logs
      description: Please copy and paste the extension logs
      placeholder: |
        To get the logs:
        1. Press Ctrl+Shift+P (or Cmd+Shift+P on Mac)
        2. Type "Scientific Data Viewer: Show Extension Logs"
        3. Copy and paste the entire log output here
    validations:
      required: false

  - type: textarea
    id: error-messages
    attributes:
      label: Error Messages
      description: Any error messages you received (from VSCode, terminal, or extension)
      placeholder: Paste any error messages here, including stack traces if available.

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context about the problem here.
      placeholder: |
        - Does this happen with all files or specific ones?
        - Did this work in a previous version?
        - Any workarounds you've found?
        - Screenshots or screen recordings if helpful

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our Code of Conduct
      options:
        - label: I have searched existing issues and this is not a duplicate
          required: true
        - label: I have read and agree to follow the [Contributing Guidelines](CONTRIBUTING.md)
          required: true
