name: ✨ Feature Request
description: Suggest a new feature or enhancement for the Scientific Data Viewer extension
title: "[Feature]: "
labels: ["enhancement", "needs-triage"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thank you for suggesting a new feature! Please provide as much detail as possible to help us understand your request.

  - type: textarea
    id: feature-description
    attributes:
      label: Feature Description
      description: A clear and concise description of the feature you'd like to see.
      placeholder: Describe the feature you want to be added to the Scientific Data Viewer extension.
    validations:
      required: true

  - type: textarea
    id: problem-statement
    attributes:
      label: Problem Statement
      description: What problem does this feature solve? What is the current limitation?
      placeholder: |
        Is your feature request related to a problem? Please describe.
        A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
    validations:
      required: true

  - type: textarea
    id: proposed-solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like to see implemented.
      placeholder: A clear and concise description of what you want to happen.
    validations:
      required: true

  - type: textarea
    id: use-cases
    attributes:
      label: Use Cases
      description: Describe specific use cases for this feature
      placeholder: |
        - Use case 1: When working with [specific data type], I need to [specific action]
        - Use case 2: When [specific scenario], I want to [specific functionality]
        - Use case 3: [Additional use cases...]
    validations:
      required: true

  - type: dropdown
    id: feature-category
    attributes:
      label: Feature Category
      description: What category does this feature fall under?
      options:
        - Data Visualization
        - File Format Support
        - User Interface
        - Performance
        - Integration
        - Configuration
        - Accessibility
        - Other
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Describe any alternative solutions or workarounds you've considered.
      placeholder: A clear and concise description of any alternative solutions or features you've considered.

  - type: textarea
    id: mockups-examples
    attributes:
      label: Mockups, Screenshots, or Examples
      description: If applicable, add mockups, screenshots, or examples to help explain your feature request.
      placeholder: |
        - Screenshots of similar features in other tools
        - Mockups or wireframes
        - Links to examples in other software
        - Code examples if relevant

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Low - Nice to have
        - Medium - Would be helpful
        - High - Important for my workflow
        - Critical - Blocking my current work
    validations:
      required: true

  - type: textarea
    id: technical-considerations
    attributes:
      label: Technical Considerations
      description: Any technical details, constraints, or considerations for implementation
      placeholder: |
        - Does this require changes to the Python backend?
        - Does this affect file format support?
        - Any performance implications?
        - Dependencies or external libraries needed?

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context about the feature request here.
      placeholder: |
        - How often would you use this feature?
        - Does this relate to any existing issues?
        - Any other relevant information?

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our Code of Conduct
      options:
        - label: I have searched existing issues and this is not a duplicate
          required: true
        - label: I have read and agree to follow the [Contributing Guidelines](CONTRIBUTING.md)
          required: true
