name: ❓ Question / Discussion
description: Ask questions about using the extension or discuss ideas before submitting a feature request
title: "[Question]: "
labels: ["question", "needs-triage"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Have a question about using the Scientific Data Viewer extension? Want to discuss an idea before submitting a feature request? This is the perfect place!

        **Before asking:**
        - Check the [README](https://github.com/etienneschalk/scientific-data-viewer#readme) for basic usage
        - Search existing [issues](https://github.com/etienneschalk/scientific-data-viewer/issues)
        - Look at the [troubleshooting section](https://github.com/etienneschalk/scientific-data-viewer#-troubleshooting) in the README

  - type: dropdown
    id: question-type
    attributes:
      label: Question Type
      description: What type of question or discussion is this?
      options:
        - How to use a specific feature
        - Workflow or best practices
        - File format support
        - Performance or optimization
        - Integration with other tools
        - Feature idea discussion
        - General usage question
        - Other
    validations:
      required: true

  - type: textarea
    id: question-description
    attributes:
      label: Your Question
      description: Please describe your question or the topic you'd like to discuss.
      placeholder: |
        What would you like to know or discuss?
        Be as specific as possible to help others understand your question.
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Context
      description: Provide context about your use case or situation
      placeholder: |
        - What are you trying to accomplish?
        - What file types are you working with?
        - What's your current workflow?
        - Any specific challenges you're facing?

  - type: textarea
    id: current-approach
    attributes:
      label: Current Approach
      description: How are you currently handling this? What have you tried?
      placeholder: |
        - What steps have you already taken?
        - What workarounds are you using?
        - What other tools are you using alongside this extension?

  - type: textarea
    id: expected-outcome
    attributes:
      label: Expected Outcome
      description: What would you like to achieve or learn?
      placeholder: |
        - What would be the ideal solution?
        - What information would be most helpful?
        - How would this improve your workflow?

  - type: textarea
    id: file-examples
    attributes:
      label: File Examples (if applicable)
      description: If your question is about specific files, please provide details
      placeholder: |
        - File format: (e.g., NetCDF, HDF5, Zarr, GRIB, GeoTIFF)
        - File size: (e.g., 50 MB)
        - How was the file created? (e.g., generated by xarray, downloaded from...)
        - Any specific attributes or structure that's relevant?

  - type: textarea
    id: environment-info
    attributes:
      label: Environment Information (if relevant)
      description: If your question is about setup or compatibility, please share your environment details
      placeholder: |
        - VSCode version:
        - Extension version:
        - Operating system:
        - Python version:
        - Any relevant package versions:

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Any other information that might be helpful
      placeholder: |
        - Screenshots or screen recordings if helpful
        - Links to related documentation or examples
        - Any other relevant information

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our Code of Conduct
      options:
        - label: I have searched existing issues and this is not a duplicate
          required: true
        - label: I have read and agree to follow the [Contributing Guidelines](CONTRIBUTING.md)
          required: true
